import React from "react";
import { Button, Card, Container, Row, Col } from "react-bootstrap";
import "./pricing.css";
import { FaArrowRight } from "react-icons/fa";
import { FaCheck } from "react-icons/fa6";
import { FaArrowRightLong } from "react-icons/fa6";

const pricingData = [
  {
    id: 1,
    title: "Business",
    description:
      "Departments and organizations who need a secure, scalable, and customizable AI platform.",
    price: "Custom Pricing",
    buttonLabel: "Contact Sales",
    buttonVariant: "primary",
    buttonColor: "rgb(163 80 229)",
    features: [
      "Unlimited features",
      "Custom templates and workflows",
      "Dedicated success manager",
      "API access",
      "Advanced admin analytics",
      "SSO with additional security review",
    ],
    cardClass: "pricing-business",
  },
  {
    id: 2,
    title: "Teams",
    description:
      "Small marketing teams who need to generate, create, and repurpose content for multiple campaigns.",
    price: "$99 ",
    buttonLabel: "Start Your 7-Day Free Trial",
    buttonVariant: "primary",
    buttonColor: "rgb(107 195 247)",
    features: [
      "Unlimited words generated by AI",
      "Includes 3 seats",
      "Access SEO mode",
      "3 Brand voices",
      "150 Knowledge assets",
      "10 Campaigns",
    ],
    cardClass: "pricing-teams",
  },
  {
    id: 3,
    title: "Creator",
    description:
      "Freelancers, marketers, and entrepreneurs ready to automate daily work in their personalized Brand Voice.",
    price: "$39",
    buttonLabel: "Start Your 7-Day Free Trial",
    buttonVariant: "primary",
    buttonColor: "rgb(245 193 104)",
    features: [
      "Unlimited words generated by AI",
      "Includes 1 seat",
      "50+ Templates",
      "1 Brand voice",
      "50 Knowledge assets",
      "Browser extension",
    ],
    cardClass: "pricing-creator",
  },
];

const PricingPlans = () => {
  return (
    <Container className="pricing-container py-5">
        <h1 className="text-center mb-4">Plan $ Pricing </h1>
      <h3 className="text-center mb-4">🌟 Most Popular</h3>
      <Row>
        {pricingData.map((plan) => (
          <Col md={4} className="pricing-card-col">
            <Card className={`pricing-card ${plan.cardClass} shadow`}>
              <Card.Body>
                <h4 className="pricing-title">{plan.title}</h4>
                <p className="pricing-description">{plan.description}</p>
                <h2 className="pricing-cost">{plan.price}</h2>
                <Button
                  className="trial-button w-100"
                  type="button"
                  style={{ backgroundColor: plan.buttonColor, color: "white" }}
                >
                  {plan.buttonLabel}
                  <span className="arrow-icon">
                    <FaArrowRightLong />
                  </span>
                </Button>
                <ul className="pricing-features">
                  {plan.features.map((feature, index) => (
                    <li key={index}>
                      {" "}
                      <FaCheck className="mx-3" />
                      {feature}
                    </li>
                  ))}
                </ul>
              </Card.Body>
            </Card>
          </Col>
        ))}
      </Row>
    </Container>
  );
};

export default PricingPlans;
